<?php

namespace Database\Seeders;

use App\Models\Siswa;
use Illuminate\Database\Seeder;

class SiswaSeeder extends Seeder
{
    public function run(): void
    {
        Siswa::insert([
            [
                'nama' => 'ABU BAKAR TSABIT GHUFRON',
                'nis' => '20389',
                'gender' => 'L',
                'alamat' => 'Sleman',
                'kontak' => '081234567890',
                'email' => 'abu.ghufron@gmail.com',
                'status_lapor_pkl' => false,
            ],
            [
                'nama' => 'ADE RAFIF DANESWARA',
                'nis' => '20390',
                'gender' => 'L',
                'alamat' => 'Sleman',
                'kontak' => '082134567891',
                'email' => 'ade.rafif@gmail.com',
                'status_lapor_pkl' => false,
            ],
            [
                'nama' => 'ADE ZAIDAN ALTHAF',
                'nis' => '20391',
                'gender' => 'L',
                'alamat' => 'Tuban',
                'kontak' => '083134567892',
                'email' => 'zaidan.althaf@gmail.com',
                'status_lapor_pkl' => false,
            ],
            [
                'nama' => 'ADHWA KHALILA RAMADHANI',
                'nis' => '20392',
                'gender' => 'P',
                'alamat' => 'Sleman',
                'kontak' => '084134567893',
                'email' => 'adhwa.ramadhani@gmail.com',
                'status_lapor_pkl' => false,
            ],
            [
                'nama' => 'ADNAN FARIS',
                'nis' => '20393',
                'gender' => 'L',
                'alamat' => 'Sleman',
                'kontak' => '085134567894',
                'email' => 'adnan.faris@gmail.com',
                'status_lapor_pkl' => false,
            ],
            [
                'nama' => 'AHMAD HANAFFI RAHMADHANI',
                'nis' => '20394',
                'gender' => 'L',
                'alamat' => 'Yogyakarta',
                'kontak' => '086134567895',
                'email' => 'ahmad.hanaffi@gmail.com',
                'status_lapor_pkl' => false,
            ],
            [
                'nama' => "AKBAR AD'HA KUSUMAWARDHANA",
                'nis' => '20395',
                'gender' => 'L',
                'alamat' => 'Bekasi',
                'kontak' => '087134567896',
                'email' => 'akbar.kusuma@gmail.com',
                'status_lapor_pkl' => false,
            ],
            [
                'nama' => 'ANDHIKA AUGUST FARNAZ',
                'nis' => '20396',
                'gender' => 'L',
                'alamat' => 'Brebes',
                'kontak' => '088134567897',
                'email' => 'andhika.farnaz@gmail.com',
                'status_lapor_pkl' => false,
            ],
            [
                'nama' => 'ANGELINA THITHIS SEKAR LANGIT',
                'nis' => '20397',
                'gender' => 'P',
                'alamat' => 'Bandar Lampung',
                'kontak' => '089134567898',
                'email' => 'angelina.sekar@gmail.com',
                'status_lapor_pkl' => false,
            ],
            [
                'nama' => 'ARIFIN NUR IHSAN',
                'nis' => '20398',
                'gender' => 'L',
                'alamat' => 'Bantul',
                'kontak' => '081234567899',
                'email' => 'arifin.ihsan@gmail.com',
                'status_lapor_pkl' => false,
            ],
            [
                'nama' => 'ARYA EKA RAHMAT PRASETYO',
                'nis' => '20399',
                'gender' => 'L',
                'alamat' => 'Sleman',
                'kontak' => '082234567800',
                'email' => 'arya.prasetyo@gmail.com',
                'status_lapor_pkl' => false,
            ],
            [
                'nama' => 'ATHIYYA HANIIFA',
                'nis' => '20400',
                'gender' => 'P',
                'alamat' => 'Sleman',
                'kontak' => '083234567801',
                'email' => 'athiyya.haniifa@gmail.com',
                'status_lapor_pkl' => false,
            ],
            [
                'nama' => 'AULIA MAHARANI',
                'nis' => '20401',
                'gender' => 'P',
                'alamat' => 'Bantul',
                'kontak' => '084234567802',
                'email' => 'aulia.maharani@gmail.com',
                'status_lapor_pkl' => false,
            ],
            [
                'nama' => 'BIJAK PUTRA FIRMANSYAH',
                'nis' => '20402',
                'gender' => 'L',
                'alamat' => 'Pekanbaru',
                'kontak' => '085234567803',
                'email' => 'bijak.firmansyah@gmail.com',
                'status_lapor_pkl' => false,
            ],
            [
                'nama' => 'CHRISTIAN JAROT FERDIANNDARU',
                'nis' => '20403',
                'gender' => 'L',
                'alamat' => 'Yogyakarta',
                'kontak' => '086234567804',
                'email' => 'christian.jarot@gmail.com',
                'status_lapor_pkl' => false,
            ],
            [
                'nama' => 'DAFFA ARYA SETA',
                'nis' => '20404',
                'gender' => 'L',
                'alamat' => 'Sleman',
                'kontak' => '087234567805',
                'email' => 'daffa.seta@gmail.com',
                'status_lapor_pkl' => false,
            ],
            [
                'nama' => 'DIMAS BAGUS AHMAD NURYASIN',
                'nis' => '20405',
                'gender' => 'L',
                'alamat' => 'Sleman',
                'kontak' => '088234567806',
                'email' => 'dimas.nuryasin@gmail.com',
                'status_lapor_pkl' => false,
            ],
            [
                'nama' => 'EKALAYA KEMAL PASHA',
                'nis' => '20406',
                'gender' => 'L',
                'alamat' => 'Yogyakarta',
                'kontak' => '089234567807',
                'email' => 'ekalaya.pasha@gmail.com',
                'status_lapor_pkl' => false,
            ],
            [
                'nama' => 'FADLY ATHALLA FAWWAZ',
                'nis' => '20407',
                'gender' => 'L',
                'alamat' => 'Yogyakarta',
                'kontak' => '081334567808',
                'email' => 'fadly.fawwaz@gmail.com',
                'status_lapor_pkl' => false,
            ],
            [
                'nama' => 'FARADILLA SYIFA NUR’AINI',
                'nis' => '20408',
                'gender' => 'P',
                'alamat' => 'Yogyakarta',
                'kontak' => '082334567809',
                'email' => 'faradilla.syifa@gmail.com',
                'status_lapor_pkl' => false,
            ],
        ]);
    }
}
